id: I7EF59F74
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:16:23.886633'
last_modified: '2022-06-18T20:16:23.886644'
parser: null
source_metadata:
  title: Accounts of the Kālacakra lineage masters by sTong ra Kun dga legs grub (unfinished)
  author: སྟོང་ར་ཀུན་དགའ་ལེགས་གྲུབ།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2020-04-13);
    unrevised OCR version, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Google Docs, OCR-processed (Tesseract)
  - Editorial process:Mathias Fermer (mf), སྨོན་བཟང་དཔེ་རྙིང་འཚོལ་བསྡུ་ཁང་། (eds)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/4724
  bases:
    c186:
      title: Accounts of the Kālacakra lineage masters by sTong ra Kun dga legs grub
        (unfinished)
      order: 1
      base_file: c186.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
